### ISSUE TITLE
RestSharp installation.

### ISSUE THREAD

**Issue by Dinomannen** [jacob-keller/L0G-101086#13]
I followed your installation guide and when i tried to run upload-logs.ps1 i got the error message: "This script requires RestSharp to be installed. Press enter to exit:".
I don't find how to install RestSharp.

**Comment by Dinomannen** [comment]
EDIT: problem was that %UserProfile% did not work in the path for the RestSharp.dll file and thus it could not read it.

**Comment by jacob-keller** [comment]
@Dinomannen, was the RestSharp dll somewhere in the %UserProfile% directory when you tried this, or did you just happen to have the path wrong?

**Comment by jacob-keller** [comment]
In v2.4.1 I've updated the error message to be more explicit about which path is being used.
