### ISSUE TITLE
Major version 1, but we expected major version 2

### ISSUE THREAD

**Issue by d3fr0st** [jacob-keller/L0G-101086#23]
When running upload-log after upgrading.

simpleArcParse has major version 1, but we expected major version 2
Please upgrade to the v2.0.0 release of simpleArcParse
Press enter to exit:

**Comment by jacob-keller** [comment]
Try re-downloading simpleArcParse.exe, I think I accidentally had the wrong version uploaded.

**Comment by jacob-keller** [comment]
This should be fixed now, but let me know if it's not.

**Comment by d3fr0st** [comment]
Yep fixed
