### ISSUE TITLE
Discord API now fails when content-type is not set

### ISSUE THREAD

**Issue by pickettd** [jacob-keller/L0G-101086#28]
**Describe the bug**
The Discord API now requires you to set the content-type when posting to the webhook (I think this was changed late last week). See [this Discord issue comment for more details](https://github.com/discordapp/discord-api-docs/issues/1197#issuecomment-558027645). So now format-encounters.ps1 is failing to post to Discord. By adding the content-type header for application/json it works again.

**To Reproduce**
1. Setup config file
2. Use upload-logs.ps1 to parse raw logs and generate metadata
3. Use format-encounters.ps1 to post to Discord webhook

**Additional context**
Here is the pull request to fix the problem: #27

**Comment by jacob-keller** [comment]
Thanks for the fix, I've merged it!
